### ISSUE TITLE
kernel8.img not working

### ISSUE THREAD

**Issue by btauro** [rsta2/circle64#1]
Hi,
I have followed all the build steps .
make has run successfully. 
I have been trying to run kernel8.img on raspberrypi3 but i just get a blank screen.
Could you please help me with this.

Thanks,

**Comment by rsta2** [comment]
You should use the latest firmware files *bootcode.bin*, *start.elf* and *fixup.dat*. You can get them using *make* in the *boot/* subdirectory. Do not provide a *config.txt* file on the SD card. It's not needed. Which sample program did you tried with which toolchain version?

**Comment by btauro** [comment]
Hey,

I have the latest firmware files using the boot make
17-fractal is the sample program
gcc-linaro-7.2.1-2017.11-x86_64_aarch64-elf toolchain.
I also followed the instructions to make it run multi core and also set "loglevel=1"
But still i get a blank screen

 lf you could please  explain how interrupts work for raspberry pi3 in your project  or point me to any links it would be great.

Thank you,

**Comment by rsta2** [comment]
This project hasn't been updated for some time. I tried it now with the GCC 7.2.1 toolchain, you have mentioned, and it seems Circle64 cannot be build with it, to run the samples successfully. Unfortunately I have not the time to debug this at the moment. You could use the toolchain which is mentioned in the *Building* section of the main *README.md*, which is proven to work. Unfortunately it's old, I know.

The exception handling in AArch64 (interrupts are exceptions too) is explained in the [ARMv8-A Reference Manual](http://infocenter.arm.com/help/topic/com.arm.doc.ddi0487a.h/index.html) in chapter D1 (AArch64 System Level Programmers’ Model) for the Cortex-A53 CPU of the Raspberry Pi 3. You have to register to be able to download this document. To apply this for the peripherals of the RPi 3 you also need the [BCM2835 ARM Peripherals](https://www.raspberrypi.org/documentation/hardware/raspberrypi/bcm2835/BCM2835-ARM-Peripherals.pdf) document, which is still valid for the BCM2837 in most parts.

The exception handling is implemented in exceptionstub.S, interrupt.cpp and exceptionhandler.cpp in Circle64 (all in the lib/ subdirectory). You should study these files to learn how it works. Excuse me, that I do not have to time to explain this all in detail.

**Comment by btauro** [comment]
Yes it worked on the older cross compiler 

Thank you

**Comment by rsta2** [comment]
I did commit an update with which it should work with the GCC 7.2.1 toolchain now. It seems the GCC optimizer has a problem with some code in the class *CTranslationTable*. Unfortunately I was not able to solve this until now, but with optimization locally disabled for these functions it should work.
