### ISSUE TITLE
USB support?

### ISSUE THREAD

**Issue by ghost** [rsta2/circle64#3]
I really like the USB support you have in circle repository - just wanted to check if you have plans to port that too to circle64?

Keep up the good (_great_) work!

**Comment by rsta2** [comment]
Thanks! There are no plans at the moment, because there hasn't been demand for it. The USPi library can be built for AArch64 and used with Circle64 at the moment. This has been discussed in [this issue](https://github.com/rsta2/uspi/issues/19).

**Comment by rsta2** [comment]
The [32-bit Circle project](https://github.com/rsta2/circle) has been ported to AArch64. It can be used with AArch32 and AArch64 now. This includes USB and TCP/IP support and all samples.
